name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Upload build artifacts to existing Release
      run: |
        release_tag="Star2DEvolution"
        release_id=$(gh release view $release_tag --json id -q ".id")
        gh release upload $release_id app/build/outputs/apk/release/app-release.apk --clobber

    # Removed the step for uploading release APK to artifacts
    # - name: Upload release APK
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: release-apk
    #     path: app/build/outputs/apk/release/app-release.apk
