name: Android CI

on:
  workflow_dispatch: # Trigger manually from the GitHub Actions UI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build with Gradle
    - name: Build with Gradle
      run: ./gradlew build

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Upload build artifacts to existing Release
      run: |
        release_tag="Star2DEvolution"
        release_id=$(gh release view $release_tag --json id -q ".id")
        gh release upload $release_id app/build/outputs/apk/debug/app-debug.apk --clobber
        
    
    # Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: engine.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    # Extract classes.dex files and zip them
    - name: Extract and Zip Classes
      if: always() # Ensure this runs even if the APK upload succeeds
      run: |
        APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
        ZIP_OUTPUT="classes.zip"
        
        # Create a temporary directory
        TEMP_DIR=$(mktemp -d)
        
        # Unzip the APK into the temporary directory
        unzip -o "$APK_PATH" -d "$TEMP_DIR"
        
        # Find all classes.dex files and zip them
        cd "$TEMP_DIR"
        
        zip "../$ZIP_OUTPUT" AndroidManifest.xml
        
        zip -r "$ZIP_OUTPUT" classes*.dex

        ls
        # Return to the workspace
        cd -
        echo "moving files .."
        echo "$TEMP_DIR/$ZIP_OUTPUT"
        
        mv "$TEMP_DIR/$ZIP_OUTPUT" .

    - name: show files list
      run: ls
      
    # Upload Classes ZIP artifact
    - name: Upload Classes ZIP
      uses: actions/upload-artifact@v4
      with:
        name: classes.zip
        path: classes.zip
