name: Android Manifest test

on:
  workflow_dispatch: # Trigger manually from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    # decode manifest 
    - name : Decode manifest 
      run : java jar assets/axml.jar d "./app/src/main/AndroidManifest.xml" ./out.xml
    # Upload APK artifact
    - name: Upload manifest artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifest.xml
        path: out.xml
